storage_type: postgres
shutdown_timeout: 5s

handler:
  host_addr: "localhost:8080"
  handle_timeout: 10s

http_server:
  listen_addr: ":8080"

postgres:
  host: localhost
  user: postgres
  password: 12345678
  dbname: postgres
