services:
  app:
    build: ./
    env_file:
      - .app_env
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
    command: ["db", "./build/go-shortener-server"]

  db:
    image: postgres
    env_file:
      - .postgres_env
    ports:
      - "5432:5432"
