openapi: 3.0.1
info:
  title: go-shortener
  description: сокращатель ссылок, написанный на языке Go
  version: 1.0.0
paths:
  /shorten:
    post:
      summary: Создать сокращенную ссылку
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                source:
                  type: string
      responses:
        '200':
          description: Ссылка успешно создана
          content:
            application/json:
              schema:
                type: object
                properties:
                  shorten_link:
                    type: string
  /{mapping}:
    get:
      summary: Получить целевую ссылку по сокращенной
      parameters:
        - in: path
          name: mapping
          required: true
          schema:
            type: string
            example: aaaaaaaaab
      responses:
        '301':
          description: Успешно перенаправлен на целевую ссылку