// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/link/link.proto

package link

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LinkShortenerServiceClient is the client API for LinkShortenerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LinkShortenerServiceClient interface {
	AddLink(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Link, error)
	GetLink(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Link, error)
}

type linkShortenerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLinkShortenerServiceClient(cc grpc.ClientConnInterface) LinkShortenerServiceClient {
	return &linkShortenerServiceClient{cc}
}

func (c *linkShortenerServiceClient) AddLink(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Link, error) {
	out := new(Link)
	err := c.cc.Invoke(ctx, "/link.LinkShortenerService/AddLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *linkShortenerServiceClient) GetLink(ctx context.Context, in *Link, opts ...grpc.CallOption) (*Link, error) {
	out := new(Link)
	err := c.cc.Invoke(ctx, "/link.LinkShortenerService/GetLink", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LinkShortenerServiceServer is the server API for LinkShortenerService service.
// All implementations must embed UnimplementedLinkShortenerServiceServer
// for forward compatibility
type LinkShortenerServiceServer interface {
	AddLink(context.Context, *Link) (*Link, error)
	GetLink(context.Context, *Link) (*Link, error)
	mustEmbedUnimplementedLinkShortenerServiceServer()
}

// UnimplementedLinkShortenerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLinkShortenerServiceServer struct {
}

func (UnimplementedLinkShortenerServiceServer) AddLink(context.Context, *Link) (*Link, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddLink not implemented")
}
func (UnimplementedLinkShortenerServiceServer) GetLink(context.Context, *Link) (*Link, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLink not implemented")
}
func (UnimplementedLinkShortenerServiceServer) mustEmbedUnimplementedLinkShortenerServiceServer() {}

// UnsafeLinkShortenerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LinkShortenerServiceServer will
// result in compilation errors.
type UnsafeLinkShortenerServiceServer interface {
	mustEmbedUnimplementedLinkShortenerServiceServer()
}

func RegisterLinkShortenerServiceServer(s grpc.ServiceRegistrar, srv LinkShortenerServiceServer) {
	s.RegisterService(&LinkShortenerService_ServiceDesc, srv)
}

func _LinkShortenerService_AddLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServiceServer).AddLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/link.LinkShortenerService/AddLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServiceServer).AddLink(ctx, req.(*Link))
	}
	return interceptor(ctx, in, info, handler)
}

func _LinkShortenerService_GetLink_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Link)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LinkShortenerServiceServer).GetLink(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/link.LinkShortenerService/GetLink",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LinkShortenerServiceServer).GetLink(ctx, req.(*Link))
	}
	return interceptor(ctx, in, info, handler)
}

// LinkShortenerService_ServiceDesc is the grpc.ServiceDesc for LinkShortenerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LinkShortenerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "link.LinkShortenerService",
	HandlerType: (*LinkShortenerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddLink",
			Handler:    _LinkShortenerService_AddLink_Handler,
		},
		{
			MethodName: "GetLink",
			Handler:    _LinkShortenerService_GetLink_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/link/link.proto",
}
